<?xml version="1.0"?>
<robot name="wheel_only_test" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Include full igvc library even though we're not using all of it -->
	<xacro:include filename="$(find igvc_description)/urdf/igvc_library.urdf.xacro"/>
	<xacro:include filename="$(find igvc_description)/urdf/igvc_materials.urdf.xacro"/>
	<xacro:include filename="$(find core_description)/urdf/sensors/cameras/c920_camera.urdf.xacro"/>
	<xacro:include filename="$(find core_description)/urdf/sensors/lasers/hokuyo.urdf.xacro"/>
	<xacro:include filename="$(find core_description)/urdf/sensors/imu/sparton_ahrs8.urdf.xacro"/>
	<xacro:include filename="$(find core_description)/urdf/sensors/gps/csi_minimax.urdf.xacro" />
	<xacro:include filename="$(find igvc_description)/urdf/igvc_properties.urdf.xacro"/>

	<!-- Base link -->
	<link name="base_link">
		<visual>
			<geometry>
				<mesh filename="package://igvc_description/meshes/Metaknight.dae" scale="1 1 1" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 -.28"/>
		</visual>
		<collision>
			<geometry>
				<mesh filename="package://igvc_description/meshes/Metaknight.dae" scale="1 1 1" />
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 -.28"/>
		</collision>
		<inertial>
			<mass value="${chassis_mass}"/>
			<inertia ixx="${chassis_ixx}" ixy="0" ixz="0" iyy="${chassis_iyy}" iyz="0" izz="${chassis_izz}"/>
		</inertial>
		<!-- Gazebo description for base_link -->
		<gazebo reference="base_link"/>
	</link>

	<!-- Base footprint as a reference to the ground beneath robot -->
	<link name="base_footprint">
		<visual>
			<geometry>
				<box size="0.001 0.001 0.001"/>
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</visual>
		<inertial>
			<mass value="0.0001"/>
			<origin xyz="0 0 0"/>
			<inertia ixx="0.0001" ixy="0.0" ixz="0.0" iyy="0.0001" iyz="0.0" izz="0.0001"/>
		</inertial>
		<gazebo reference="base_footprint"/>
	</link>

	<!-- Joint connecting base_link to the footprint -->
	<joint name="base_footprint_joint" type="fixed">
		<origin xyz="0 0 ${chassis_height/2}"/>
		<parent link="base_footprint"/>
		<child link="base_link"/>
		<gazebo reference="base_footprint_joint"/>
	</joint>

	<!-- Attach front_front_fake_laser frame -->
	<link name="front_fake_laser">
		<visual>
			<geometry>
				<box size="0.001 0.001 0.001" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</visual>
	</link>
	<joint name="front_fake_laser_joint" type="fixed">
		<origin xyz="1.22 0 0"/>
		<parent link="base_link"/>
		<child link="front_fake_laser"/>
	</joint>

	<link name="left_fake_laser">
		<visual>
			<geometry>
				<box size="0.001 0.001 0.001" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</visual>
	</link>
	<joint name="left_fake_laser_joint" type="fixed">
		<origin xyz="0.53 0.55 0" rpy="0 0 0.7854"/>
		<parent link="base_link"/>
		<child link="left_fake_laser"/>
	</joint>

	<link name="right_fake_laser">
		<visual>
			<geometry>
				<box size="0.001 0.001 0.001" />
			</geometry>
			<origin xyz="0 0 0" rpy="0 0 0"/>
		</visual>
	</link>
	<joint name="right_fake_laser_joint" type="fixed">
		<origin xyz="0.46 -0.53 0" rpy="0 0 -0.7854"/>
		<parent link="base_link"/>
		<child link="right_fake_laser"/>
	</joint>

	<!-- Add the wheels -->
	<igvc_wheel parent="base_link" lr="right" reflectY="-1"/>
	<igvc_wheel parent="base_link" lr="left" reflectY="1"/>

	<!-- Add the casters -->
	<igvc_caster parent="base_link" lr="right" reflectY="-1"/>
	<igvc_caster parent="base_link" lr="left" reflectY="1"/>

	<!-- Add a camera -->
	<c920_camera identifier="left" parent="base_link" xPos="0.1397" yPos="0.203" zPos="0.158" roll="0" pitch="0.35" yaw="0.524"/>
	<c920_camera identifier="front" parent="base_link" xPos="-0.273" yPos="0.0" zPos="0.9" roll="0" pitch="0.35" yaw="0"/>
	<c920_camera identifier="right" parent="base_link" xPos="0.1397" yPos="-0.203" zPos="0.158" roll="0" pitch="0.35" yaw="-0.524"/>

	<!-- Add a laser -->
	<hokuyo_utm30lx parent="base_link" xPos="0.294" yPos="0" zPos="0.317" roll="0" pitch="0" yaw="0"/>

	<!-- Add AHRS-8 -->
	<sparton_ahrs8 parent="base_link" xPos="-0.5842" yPos="0" zPos="0" roll="0" pitch="0" yaw="3.14159"/>

	<!-- Add GPS -->
	<minimax_gps parent="base_link" xPos="-0.381" yPos="0" zPos="1.09" roll="0" pitch="0" yaw="0" />

	<!-- Set up miscellaneous igvc plugins not related to sensors -->
	<igvc_gazebo />

	<gazebo reference="igvc"/>
</robot>
