<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Include IGVC properties and materials -->
	<xacro:include filename="$(find igvc_description)/urdf/igvc_properties.urdf.xacro"/>

	<!-- Complete macro for placing a caster for the IGVC 2015 vehicle -->
	<xacro:macro name="igvc_caster" params="parent lr reflectY">

		<!-- Caster rotator link -->
		<link name="${lr}_caster_rotator">
			<visual>
				<geometry>
					<cylinder length="${caster_rotator_width}" radius="${caster_rotator_radius}"/>
				</geometry>
				<material name="black"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="${caster_rotator_width}" radius="${caster_rotator_radius}"/>
				</geometry>
			</collision>
			<inertial>
				<mass value="${caster_rotator_mass}"/>
				<inertia ixx="${caster_rotator_ixx}" ixy="0" ixz="0" iyy="${caster_rotator_iyy}" iyz="0" izz="${caster_rotator_izz}"/>
			</inertial>
		</link>

		<gazebo reference="${lr}_caster_rotator"/>

		<!-- Caster rotator joint -->
		<joint name="${lr}_caster_rotator_joint" type="continuous">
			<parent link="${parent}"/>
			<child link="${lr}_caster_rotator"/>
			<axis xyz="0 0 1"/>
			<origin xyz="${caster_x_pos} ${reflectY * caster_y_pos} ${caster_z_pos}"/>
			<limit effort="100.0" velocity="0.0"/>
		</joint>

		<gazebo reference="${lr}_caster_rotator_joint"/>

		<!-- Caster wheel link -->
		<link name="${lr}_caster_wheel">
			<visual>
				<geometry>
					<cylinder length="${caster_wheel_width}" radius="${caster_wheel_radius}"/>
				</geometry>
				<origin rpy="${M_PI/2} 0 0"/>
				<material name="black"/>
			</visual>
			<collision>
				<geometry>
					<cylinder length="${caster_wheel_width}" radius="${caster_wheel_radius}"/>
				</geometry>
				<origin rpy="${M_PI/2} 0 0"/>
			</collision>
			<inertial>
				<mass value="${caster_wheel_mass}"/>
				<inertia ixx="${caster_wheel_ixx}" ixy="0.0" ixz="0.0" iyy="${caster_wheel_iyy}" iyz="0.0" izz="${caster_wheel_izz}"/>
			</inertial>
		</link>

		<!-- Caster wheel Gazebo specification -->
		<gazebo reference="${lr}_caster_wheel">
			<mu1>0.0</mu1>
			<mu2>0.0</mu2>
			<kp>10000000.0</kp>
			<kd>100.0</kd>
		</gazebo>

		<!-- Caster wheel joint -->
		<joint name="${lr}_caster_wheel_joint" type="continuous">
			<parent link="${lr}_caster_rotator"/>
			<child link="${lr}_caster_wheel"/>
			<axis xyz="0 1 0"/>
			<origin xyz="0 0 -${caster_wheel_radius + 0.01}"/>
			<limit effort="100.0" velocity="0.0"/>
		</joint>

		<gazebo reference="${lr}_caster_wheel_joint"/>

	</xacro:macro>
</robot>