<?xml version="1.0"?>
<robot name="igvc_gazebo" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- Set up for all model plugins -->
	<xacro:macro name="igvc_gazebo">
	
	<!-- Include properties file -->
	<xacro:include filename="$(find igvc_description)/urdf/igvc_properties.urdf.xacro"/>
		<gazebo>
			<!-- Differential Drive Plugin -->
			<plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
				<alwaysOn>true</alwaysOn>
				<updateRate>100.0</updateRate>
				<!-- Joints have to be set BACKWARDS from what we expect -->
				<!-- Not sure why, assume they define left and right from a head on view -->
				<leftJoint>right_wheel_joint</leftJoint>
				<rightJoint>left_wheel_joint</rightJoint>
				<wheelSeparation>${chassis_width + wheel_width/2}</wheelSeparation>
				<wheelDiameter>${2*wheel_radius}</wheelDiameter>
				<wheelTorque>27</wheelTorque>
				<robotBaseFrame>base_footprint</robotBaseFrame>
				<odometryFrame>map</odometryFrame>
				<publishWheelJointState>true</publishWheelJointState>
				<publishWheelTF>true</publishWheelTF>
			</plugin>

			<!-- Ros Control Plugin -->
			<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so"/>

			<!-- Joint State Publisher for non-actuated joints -->
			<!-- Place any joints we want published in the jointName tag -->
			<plugin name="gazebo_ros_joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
				<jointName>left_caster_wheel_joint, right_caster_wheel_joint, left_caster_rotator_joint, right_caster_rotator_joint</jointName>
			</plugin>
			
		</gazebo>
	</xacro:macro>
</robot>
